"""Settings resolution and shared plumbing.

Resolution order, highest first: ``FRAPPE_MAILCATCH_*`` environment variables,
then values baked in by Nix (``_baked.py``, generated at build time), then the
defaults below. Env wins so a running process can be re-pointed without a
rebuild; the baked values mean the catcher still works when the devenv
environment is absent (an editor terminal, ``nix run``, a stray ``sudo -u``).

Settings are read at *call* time rather than frozen at import, matching
odoo-nix's ``_settings()``.
"""

import os
import sys

try:  # generated by Nix next to this file; absent in a bare source checkout
    from ._baked import BAKED
except ImportError:  # pragma: no cover - exercised by the source-tree unit check
    BAKED = {}

DEFAULTS = {
    "enabled": True,
    "host": "127.0.0.1",
    "port": 1025,
    "http_port": 8025,
    "sender": "notifications@example.com",
    "unmute": True,
    "pop3_enabled": False,
    "pop3_port": 1110,
    "pop3_user": "dev",
    "pop3_password": "dev",
}

_TRUTHY = {"1", "true", "yes", "on", "t", "y"}
_FALSY = {"0", "false", "no", "off", "f", "n", ""}


class MailcatchBlocked(OSError):
    """Raised when a connection the catcher refuses to proxy is attempted.

    Subclasses ``OSError`` so callers that already handle "cannot reach the
    mail server" degrade the way they would for an unreachable host.
    """


class MailcatchPatchError(RuntimeError):
    """A patch target went missing — Frappe's internals moved.

    Raised from inside the post-import hook so the offending ``import`` fails
    loudly instead of leaving a silently inert interceptor behind.
    """


def _as_bool(value, fallback):
    if isinstance(value, bool):
        return value
    if value is None:
        return fallback
    text = str(value).strip().lower()
    if text in _TRUTHY:
        return True
    if text in _FALSY:
        return False
    return fallback


def _as_int(value, fallback):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        warn(f"invalid integer {value!r}; falling back to {fallback!r}")
        return fallback


def _raw(key):
    env = os.environ.get("FRAPPE_MAILCATCH_" + key.upper())
    if env is not None and env.strip() != "":
        return env
    if key in BAKED:
        return BAKED[key]
    return DEFAULTS[key]


class Settings:
    """Lazily-resolved view of the catcher configuration."""

    __slots__ = ()

    @property
    def enabled(self):
        return _as_bool(_raw("enabled"), DEFAULTS["enabled"])

    @property
    def host(self):
        return str(_raw("host"))

    @property
    def port(self):
        return _as_int(_raw("port"), DEFAULTS["port"])

    @property
    def http_port(self):
        return _as_int(_raw("http_port"), DEFAULTS["http_port"])

    @property
    def sender(self):
        return str(_raw("sender"))

    @property
    def unmute(self):
        return _as_bool(_raw("unmute"), DEFAULTS["unmute"])

    @property
    def pop3_enabled(self):
        return _as_bool(_raw("pop3_enabled"), DEFAULTS["pop3_enabled"])

    @property
    def pop3_port(self):
        return _as_int(_raw("pop3_port"), DEFAULTS["pop3_port"])

    @property
    def pop3_user(self):
        return str(_raw("pop3_user"))

    @property
    def pop3_password(self):
        return str(_raw("pop3_password"))

    @property
    def block_incoming(self):
        """Incoming is blocked unless it has somewhere safe to point."""
        return not self.pop3_enabled


_SETTINGS = Settings()


def settings():
    return _SETTINGS


_ANNOUNCED = False


def announce():
    """Emit the activation banner once per process, on first interception.

    Deferred rather than printed at import so that the many Python processes a
    bench starts which never touch mail (``bench build``, tooling, editor
    helpers) stay quiet.
    """
    global _ANNOUNCED
    if _ANNOUNCED:
        return
    _ANNOUNCED = True
    st = settings()
    detail = f"ALL outgoing email is redirected to {st.host}:{st.port}"
    if st.pop3_enabled:
        detail += f", incoming is served from {st.host}:{st.pop3_port} (POP3)"
    else:
        detail += ", incoming (IMAP/POP3) is blocked"
    warn(f"ACTIVE — {detail}. Web UI: http://{st.host}:{st.http_port}")


def warn(message):
    sys.stderr.write(f"WARNING frappe_mailcatch {message}\n")
