"""Keep frappe-nix's dev environment on an upstream Frappe revision.

Three things follow the Frappe that dev/uv.lock pins:

- the pin itself: [tool.uv.sources].frappe in dev/pyproject.toml is an archive
  URL for one commit of the branch named in [tool.frappe-nix].frappe-branch;
- dev/frappe-ruff.toml: that commit's pyproject.toml [tool.ruff], verbatim, in
  ruff.toml form. The root ruff.toml extends it;
- the ruff in dev/pyproject.toml's dev group: the ruff-pre-commit rev in that
  commit's .pre-commit-config.yaml, so formatting here matches upstream.

  frappe-upstream pin   ROOT      point the URL at the branch tip
  frappe-upstream sync  SRC ROOT  rewrite frappe-ruff.toml and the ruff pin
  frappe-upstream check SRC ROOT  exit 1 if either has drifted from SRC

SRC is the unpacked Frappe source; ROOT is the frappe-nix checkout. `check` is
the frappe-upstream-config flake check.
"""

import re
import subprocess
import sys
import tomllib
from pathlib import Path

import tomlkit

ARCHIVE = "https://github.com/frappe/frappe/archive/{rev}.tar.gz"

HEADER = """\
# Generated by `sync-frappe-upstream` from the Frappe revision dev/uv.lock pins:
# its pyproject.toml [tool.ruff], verbatim. Do not edit; frappe-nix's own
# overrides belong in the root ruff.toml, which extends this file.
"""

RUFF_REV = re.compile(r"repo:\s*https://github\.com/astral-sh/ruff-pre-commit\s+rev:\s*v?(\S+)")


def locked_version(root: Path, name: str) -> str | None:
	lock = tomllib.loads((root / "dev" / "uv.lock").read_text())
	return next((p["version"] for p in lock.get("package", []) if p["name"] == name), None)


def upstream_ruff(src: Path) -> dict:
	return tomllib.loads((src / "pyproject.toml").read_text())["tool"]["ruff"]


def upstream_ruff_version(src: Path) -> str:
	match = RUFF_REV.search((src / ".pre-commit-config.yaml").read_text())
	if not match:
		sys.exit("frappe-upstream: no ruff-pre-commit rev in Frappe's .pre-commit-config.yaml")
	return match.group(1)


def check(src: Path, root: Path) -> None:
	drift = []
	mirrored = tomllib.loads((root / "dev" / "frappe-ruff.toml").read_text())
	if mirrored != upstream_ruff(src):
		drift.append("dev/frappe-ruff.toml no longer matches the pinned Frappe's [tool.ruff].")
	want, have = upstream_ruff_version(src), locked_version(root, "ruff")
	if want != have:
		drift.append(f"dev/uv.lock has ruff {have}; the pinned Frappe's pre-commit config uses {want}.")
	if drift:
		sys.exit(
			"\n".join(drift) + "\n\nRun `sync-frappe-upstream` in the dev shell (or `update-frappe` to move"
			"\nto the branch tip first) and commit the result."
		)
	print("frappe-upstream: in sync")


def pin(root: Path) -> None:
	path = root / "dev" / "pyproject.toml"
	doc = tomlkit.parse(path.read_text())
	branch = doc["tool"]["frappe-nix"]["frappe-branch"]
	out = subprocess.run(
		["git", "ls-remote", "https://github.com/frappe/frappe", f"refs/heads/{branch}"],
		capture_output=True,
		check=True,
		text=True,
	).stdout.split()
	if not out:
		sys.exit(f"frappe-upstream: Frappe has no branch {branch!r}")
	doc["tool"]["uv"]["sources"]["frappe"]["url"] = ARCHIVE.format(rev=out[0])
	path.write_text(tomlkit.dumps(doc))
	print(f"dev/pyproject.toml: frappe → {branch} @ {out[0][:12]}")


def sync(src: Path, root: Path) -> None:
	# Re-rooted, so [tool.ruff.lint] is written as ruff.toml's [lint].
	ruff = tomlkit.document()
	for key, value in tomlkit.parse((src / "pyproject.toml").read_text())["tool"]["ruff"].items():
		ruff.add(key, value)
	(root / "dev" / "frappe-ruff.toml").write_text(HEADER + "\n" + tomlkit.dumps(ruff).lstrip())

	version = upstream_ruff_version(src)
	path = root / "dev" / "pyproject.toml"
	doc = tomlkit.parse(path.read_text())
	dev = doc["dependency-groups"]["dev"]
	idx = next((i for i, req in enumerate(dev) if re.match(r"ruff\b", str(req))), None)
	if idx is None:
		dev.append(f"ruff=={version}")
	else:
		dev[idx] = f"ruff=={version}"
	path.write_text(tomlkit.dumps(doc))
	print(f"dev/frappe-ruff.toml synced; ruff=={version}")


def main() -> None:
	cmd, *args = sys.argv[1:] or [""]
	match cmd, args:
		case "pin", [root]:
			pin(Path(root))
		case "sync", [src, root]:
			sync(Path(src), Path(root))
		case "check", [src, root]:
			check(Path(src), Path(root))
		case _:
			sys.exit(__doc__)


if __name__ == "__main__":
	main()
