"""N2's managed file, ``scripts/vite-register.mjs`` (docs/app-standards/spec.md S30, §5.11, C8),
on throwaway apps. That the region it shares with ``lib/js/vite-register.cjs`` is the same text,
and that it registers bundles when run, are nix checks (tests/standards/assets.nix)."""

import json
import re

from frappe_nix_tools.scaffold import manifest
from scaffold_helpers import AppCase

BEGIN = "// vite-register:begin\n"
END = "// vite-register:end\n"


def region(text: str) -> str:
	return text[text.index(BEGIN) : text.index(END) + len(END)]


class ViteApp(AppCase):
	def vite_app(self, build: str = "vite build") -> None:
		self.write("vite.config.ts", "export default {};\n")
		self.write("package.json", json.dumps({"name": "demo-app", "scripts": {"build": build}}))
		self.commit()

	def build_script(self) -> str:
		return json.loads(self.read("package.json"))["scripts"]["build"]


class TestShipped(ViteApp):
	def test_the_package_ships_it(self):
		self.assertTrue(manifest.ships(manifest.VITE_REGISTER))
		entry = next(e for e in manifest.load().entries if e.path == manifest.VITE_REGISTER)
		self.assertEqual(
			(entry.fragment, entry.module, entry.when), ("assets.json", "vite-register", "discover.vite")
		)

	def test_a_vite_app_gets_it_and_c8_holds(self):
		self.vite_app()
		self.synced()
		text = self.read("scripts/vite-register.mjs")
		self.assertTrue(text.startswith("// frappe-nix:managed — generated by frappe-nix"), text[:120])
		self.assertIn("do not edit.", text.splitlines()[0])
		self.assertIn('import fs from "node:fs";', text)
		self.assertIn("register({ appDir, app, sitesDir });", text)
		self.assertNotIn("{%", text)
		self.assertNotIn("{#", text)
		self.assertEqual(self.build_script(), "vite build && node scripts/vite-register.mjs")
		self.assertEqual(self.fn("compat")[0], 0)

	def test_tabs_by_default_spaces_when_asked(self):
		self.vite_app()
		self.synced()
		tabs = region(self.read("scripts/vite-register.mjs"))
		self.assertIn("\n\treturn keys;\n", tabs)
		self.table("js.format-tabs = false\n")
		self.commit()
		self.assertEqual(self.fn("sync", "--write")[0], 0)
		spaces = region(self.read("scripts/vite-register.mjs"))
		self.assertNotIn("\t", spaces)
		self.assertEqual(spaces, tabs.replace("\t", "  "))

	def test_update_assets_is_retired_and_its_step_replaced(self):
		self.write("update-assets.mjs", "\n")
		self.vite_app("vite build && node update-assets.mjs")
		self.synced()
		self.assertFalse((self.root / "update-assets.mjs").exists())
		self.assertEqual(self.build_script(), "vite build && node scripts/vite-register.mjs")

	def test_a_build_without_the_step_is_c8_and_drift(self):
		self.vite_app()
		self.synced()
		pkg = json.loads(self.read("package.json"))
		pkg["scripts"]["build"] = "vite build"
		self.write("package.json", json.dumps(pkg, indent="\t") + "\n")
		self.commit()
		code, out, _ = self.fn("compat")
		self.assertEqual(code, 1, out)
		self.assertIn("C8", out)
		code, out = self.check()
		self.assertEqual(code, 1, out)
		self.assertIn("package.json", out)

	def test_an_edited_copy_is_drift(self):
		self.vite_app()
		self.synced()
		self.write("scripts/vite-register.mjs", self.read("scripts/vite-register.mjs") + "// mine\n")
		code, out = self.check()
		self.assertEqual(code, 1, out)
		self.assertIn("scripts/vite-register.mjs (whole)", out)


class TestNotLive(ViteApp):
	def test_no_vite_no_file(self):
		self.synced()
		self.assertFalse((self.root / "scripts/vite-register.mjs").exists())

	def test_module_off_removes_it_and_its_build_step(self):
		self.vite_app()
		self.synced()
		self.assertTrue((self.root / "scripts/vite-register.mjs").exists())
		self.write(
			"pyproject.toml",
			self.read("pyproject.toml") + "\n[tool.frappe-nix.vite-register]\nenable = false\n",
		)
		self.commit()
		self.assertEqual(self.fn("sync", "--write")[0], 0)
		self.assertFalse((self.root / "scripts/vite-register.mjs").exists())
		self.assertEqual(self.build_script(), "vite build")
		self.commit()
		self.assertEqual(self.check()[0], 0)
		self.assertEqual(self.fn("compat")[0], 0)


class TestMinimal(ViteApp):
	profile = "minimal"

	def test_minimal_renders_no_registration(self):
		self.vite_app()
		self.synced()
		self.assertFalse((self.root / "scripts/vite-register.mjs").exists())
		self.assertEqual(self.build_script(), "vite build")


class TestTemplateText(ViteApp):
	def test_the_region_fits_in_80_columns(self):
		"""So oxfmt at any printWidth from 80 up leaves it as it is (the nix check runs oxfmt)."""
		self.vite_app()
		self.synced()
		for line in region(self.read("scripts/vite-register.mjs")).splitlines():
			self.assertLessEqual(len(line.replace("\t", "  ")), 80, line)
			self.assertIsNone(re.search(r"[ \t]+$", line), line)
