"""Settings resolution and shared exception types.

Resolution order, highest first: ``FRAPPE_DEVGUARD_*`` environment variables,
then the runtime file (see below), then values baked in by Nix (``_baked.py``,
generated at build time), then the defaults below. Env wins so a running
process can be re-pointed without a rebuild; the baked values mean the guards
still hold when the devenv environment is absent (an editor terminal,
``nix run``, a stray ``sudo -u``).

The runtime file exists because a couple of settings are only *known* once the
processes start: Mailpit's ports go through devenv's allocator, which walks
forward if the bench's derived port is taken, so the port Nix baked in can be
one or two below the one Mailpit actually bound. ``devenv up`` writes the
resolved values to ``$DEVENV_RUNTIME/devguard-runtime.json`` and this reads
them back.

It sits *below* env and *above* baked on purpose. Putting the ports there
instead of baking them would have been simpler but wrong: outside the devenv
environment ``DEVENV_RUNTIME`` is unset, so the mail guard would fall back to
the stock 1025 — which on a machine running several benches is *another
project's* Mailpit. Falling back to this bench's own derived base is contained;
falling back to a shared default is a cross-project mail leak, in the one guard
that offers transport-level containment.

Settings are read at *call* time rather than frozen at import, so a guard can
be turned off for a single command without a rebuild.
"""

import json
import os
import sys

try:  # generated by Nix next to this file; absent in a bare source checkout
    from ._baked import BAKED
except ImportError:  # pragma: no cover - exercised by the source-tree unit check
    BAKED = {}

#: Every guard, and its defaults. A guard's key here is the name used by
#: ``FRAPPE_DEVGUARD_DISABLE`` and by the Nix option ``devguard.<name>``.
DEFAULTS = {
    "enabled": True,
    "guards": {
        "mail": {
            "enable": True,
            "host": "127.0.0.1",
            "port": 1025,
            "http_port": 8025,
            "sender": "notifications@example.com",
            "unmute": True,
            "pop3_enabled": False,
            "pop3_port": 1110,
            "pop3_user": "dev",
            "pop3_password": "dev",
        },
        "backups": {"enable": True},
        "objectstore": {"enable": True},
        "integrations": {"enable": True, "allow_hosts": []},
        "google": {"enable": True},
        "webhooks": {"enable": True},
        "plaid": {"enable": True},
        "scheduler": {
            "enable": True,
            "block_server_scripts": True,
            # Matched EXACT-STRING against Scheduled Job Type.method. Never
            # substring: hourly_maintenance also runs
            # frappe.desk.page.backups.backups.delete_downloadable_backups,
            # a purely local retention reaper, and matching "backup" loosely
            # would disable it and fill the disk.
            "blocked_jobs": [
                "frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily",
                "frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_weekly",
                "frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily",
                "frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_weekly",
                "frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_monthly",
                "frappe.integrations.doctype.google_drive.google_drive.daily_backup",
                "frappe.integrations.doctype.google_drive.google_drive.weekly_backup",
            ],
            # Unioned with blocked_jobs, so a consumer adds to the list above
            # rather than restating it.
            "extra_blocked_jobs": [],
        },
    },
}

_TRUTHY = {"1", "true", "yes", "on", "t", "y"}
_FALSY = {"0", "false", "no", "off", "f", "n", ""}


class DevGuardBlocked(OSError):
    """Raised when a guard refuses an action that would reach production.

    Subclasses ``OSError`` so callers that already handle "the remote service
    is unreachable" degrade the way they would for a network failure.
    """


class DevGuardPatchError(RuntimeError):
    """A patch target went missing — Frappe's internals moved.

    Raised from inside the post-import hook so the offending ``import`` fails
    loudly instead of leaving a silently inert guard behind.
    """


def _as_bool(value, fallback):
    if isinstance(value, bool):
        return value
    if value is None:
        return fallback
    text = str(value).strip().lower()
    if text in _TRUTHY:
        return True
    if text in _FALSY:
        return False
    return fallback


def _as_int(value, fallback):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        warn(f"invalid integer {value!r}; falling back to {fallback!r}")
        return fallback


def _as_list(value):
    if isinstance(value, (list, tuple)):
        return list(value)
    if value is None:
        return []
    return [item.strip() for item in str(value).split(",") if item.strip()]


def _env(*parts):
    name = "_".join(["FRAPPE_DEVGUARD", *parts]).upper()
    value = os.environ.get(name)
    return value if value is not None and value.strip() != "" else None


def _runtime_path():
    explicit = os.environ.get("FRAPPE_DEVGUARD_RUNTIME")
    if explicit:
        return explicit
    runtime = os.environ.get("DEVENV_RUNTIME")
    return os.path.join(runtime, "devguard-runtime.json") if runtime else None


#: Cache keyed on the resolved path, so a `devenv up` that rewrites the file
#: under a long-lived worker still takes effect on the next process, while
#: Settings.get() — called on every guard invocation by design — does not stat
#: and parse JSON each time.
_RUNTIME_CACHE = {}


def _runtime():
    path = _runtime_path()
    if path is None:
        return {}
    if path in _RUNTIME_CACHE:
        return _RUNTIME_CACHE[path]
    try:
        with open(path) as handle:
            loaded = json.load(handle)
    except (OSError, ValueError):
        # Absent outside devenv, and unreadable is not worth failing a guard
        # over — the baked values below are a safe fallback by construction.
        loaded = {}
    _RUNTIME_CACHE[path] = loaded
    return loaded


class Settings:
    """Lazily-resolved view of the guard configuration."""

    __slots__ = ()

    @property
    def enabled(self):
        return _as_bool(_env("enabled") or BAKED.get("enabled"), DEFAULTS["enabled"])

    @property
    def disabled_guards(self):
        """Guards switched off for this process by ``FRAPPE_DEVGUARD_DISABLE``."""
        return {name.lower() for name in _as_list(_env("disable"))}

    def guard_enabled(self, guard):
        if not self.enabled or guard in self.disabled_guards:
            return False
        return _as_bool(self.get(guard, "enable"), True)

    def get(self, guard, key, cast=None):
        """Resolve one setting: env, then runtime file, then baked, then default."""
        value = _env(guard, key)
        if value is None:
            value = _runtime().get("guards", {}).get(guard, {}).get(key)
        if value is None:
            value = BAKED.get("guards", {}).get(guard, {}).get(key)
        if value is None:
            value = DEFAULTS["guards"].get(guard, {}).get(key)
        return cast(value) if cast is not None and value is not None else value

    def flag(self, guard, key, fallback=True):
        return _as_bool(self.get(guard, key), fallback)

    def number(self, guard, key, fallback=0):
        return _as_int(self.get(guard, key), fallback)

    def text(self, guard, key, fallback=""):
        value = self.get(guard, key)
        return fallback if value is None else str(value)

    def items(self, guard, key):
        return _as_list(self.get(guard, key))

    # -- mail, which has enough settings to deserve named accessors ---------

    @property
    def mail_host(self):
        return self.text("mail", "host", "127.0.0.1")

    @property
    def mail_port(self):
        return self.number("mail", "port", 1025)

    @property
    def mail_http_port(self):
        return self.number("mail", "http_port", 8025)

    @property
    def mail_sender(self):
        return self.text("mail", "sender", "notifications@example.com")

    @property
    def mail_unmute(self):
        return self.flag("mail", "unmute")

    @property
    def pop3_enabled(self):
        return self.flag("mail", "pop3_enabled", False)

    @property
    def pop3_port(self):
        return self.number("mail", "pop3_port", 1110)

    @property
    def pop3_user(self):
        return self.text("mail", "pop3_user", "dev")

    @property
    def pop3_password(self):
        return self.text("mail", "pop3_password", "dev")

    @property
    def block_incoming(self):
        """Incoming mail is blocked unless it has somewhere safe to point."""
        return not self.pop3_enabled


_SETTINGS = Settings()


def settings():
    return _SETTINGS


def warn(message):
    sys.stderr.write(f"WARNING frappe_devguard {message}\n")
