# frappe-nix:managed — generated by frappe-nix (`frappe-init --sync`); edit only inside the frappe-nix:local region.
# App-specific Nix goes in nix/local.nix, a flake-parts module imported below when it exists.
{
  description = "spa_app: SPA App";

  inputs = {
    frappe-nix.url = "github:Avunu/frappe-nix/release-1";
    nixpkgs.follows = "frappe-nix/nixpkgs";
    frappe = {
      url = "github:frappe/frappe/version-16";
      flake = false;
    };
    # frappe-nix:local-begin inputs
    # frappe-nix:local-end inputs
  };

  nixConfig = {
    extra-substituters = [ "https://devenv.cachix.org" ];
    extra-trusted-public-keys = [
      "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
    ];
  };

  outputs =
    { frappe-nix, ... }@inputs:
    frappe-nix.lib.mkFlake { inherit inputs; } (
      { lib, ... }:
      {
        imports = [
          frappe-nix.flakeModules.default
        ]
        ++ lib.optional (builtins.pathExists ./nix/local.nix) ./nix/local.nix;

        systems = [
          "aarch64-darwin"
          "aarch64-linux"
          "x86_64-darwin"
          "x86_64-linux"
        ];

        perSystem =
          { pkgs, ... }:
          {
            formatter = pkgs.nixfmt;
            frappe-nix = {
              enable = true;
              siteName = "spa-app.localhost";
              app = {
                enable = true;
                frappeVersion = "version-16";
                inherit (inputs) frappe;
                siblings = [ ];
              };
            };
          };
      }
    );
}
