"""Rendering: the one fixed Jinja configuration, the headers, and the template helpers.

The environment is fixed (spec §3.4): ``StrictUndefined``, ``trim_blocks``,
``lstrip_blocks`` and ``keep_trailing_newline``, templates read from
``frappe_nix_tools/data/templates`` through ``importlib.resources``, or from an org
profile's ``templates/`` for an override or an ``[[extra-files]]`` template (§8.1), with
the same configuration. Templates get:

- filters ``json`` / ``jsonc`` (oxfmt-formatted JSON), ``json_string`` (one quoted string),
  ``nix_string`` (a Nix string literal) and ``glob_to_regex`` (§2.14);
- functions ``rev(url, floor)`` and ``pin(action, sha, version)`` (floors, §3.2), bound to
  the file being rendered, and ``gen`` (``scaffold.configs.Gen``).
"""

import ast
import json
import operator
import os
from collections.abc import Callable
from functools import cache
from pathlib import Path
from typing import Any

import jinja2
from jinja2.sandbox import ImmutableSandboxedEnvironment, SecurityError

from frappe_nix_tools.common import data_path
from frappe_nix_tools.common.report import ConfigError
from frappe_nix_tools.scaffold import configs, floors, globs, jsonfmt

MARKER = "frappe-nix:managed"
BASE = f"{MARKER} — generated by frappe-nix (`frappe-init --sync`);"


def header(kind: str, local: bool, note: str = "") -> str:
	"""The managed header line for a ``kind`` of file (§3.6); empty for ``none``."""
	if kind == "none":
		return ""
	text = f"{BASE} {'edit only inside the frappe-nix:local region.' if local else 'do not edit.'}"
	if note:
		text += f" {note}"
	prefix = "//" if kind in ("jsonc", "ts") else "#"
	return f"{prefix} {text}\n"


def nix_string(value: str) -> str:
	escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${")
	return f'"{escaped}"'


def _configure(env: jinja2.Environment) -> jinja2.Environment:
	env.filters["json"] = lambda v: jsonfmt.dumps(v)
	env.filters["jsonc"] = lambda v: jsonfmt.dumps(v, jsonc=True)
	env.filters["json_string"] = lambda v: json.dumps(v, ensure_ascii=False)
	env.filters["nix_string"] = nix_string
	env.filters["glob_to_regex"] = globs.glob_to_regex
	return env


def _link_error(rel: str) -> ConfigError:
	return ConfigError(
		f"the profile's templates/{rel} is a symlink: a profile's templates are read only as regular"
		" files, never through a link (an in-repo profile is part of the pull request --check runs on)"
	)


def template_files(directory: Path) -> list[Path]:
	"""Every file under a profile's ``templates/``, sorted; a symlink anywhere in it (a file
	or a directory, dangling or not) is exit 2, unread: ``--check`` renders an in-repo
	profile's templates on untrusted pull requests, and a link would print what it reaches."""
	out: list[Path] = []
	for dirpath, dirnames, filenames in os.walk(directory):
		here = Path(dirpath)
		for name in [*dirnames, *filenames]:
			if (here / name).is_symlink():
				raise _link_error((here / name).relative_to(directory).as_posix())
		out += [here / name for name in filenames]
	return sorted(out)


class _NoLinkLoader(jinja2.FileSystemLoader):
	"""A ``FileSystemLoader`` that refuses a template reached through a symlink (exit 2), so an
	``include`` or an override can never read outside the profile's ``templates/``."""

	def get_source(
		self, environment: jinja2.Environment, template: str
	) -> tuple[str, str, Callable[[], bool]]:
		pieces = jinja2.loaders.split_template_path(template)
		for searchpath in self.searchpath:
			base = Path(searchpath)
			if base.is_symlink():
				raise _link_error("")
			cur = base
			for i, piece in enumerate(pieces):
				cur = cur / piece
				if cur.is_symlink():
					raise _link_error("/".join(pieces[: i + 1]))
		return super().get_source(environment, template)


def _environment(directory: str, *, links: bool = True) -> jinja2.Environment:
	# Sandboxed: an org profile's templates and [[extra-files]] paths are data a pull request
	# can change (an in-repo profile), and --check renders them on untrusted PRs. The sandbox
	# refuses the attribute walks (``cycler.__init__.__globals__``) that reach Python, and the
	# immutable one also keeps a template from changing the context the next file renders with.
	return _configure(
		ImmutableSandboxedEnvironment(
			loader=jinja2.FileSystemLoader(directory) if links else _NoLinkLoader(directory),
			undefined=jinja2.StrictUndefined,
			trim_blocks=True,
			lstrip_blocks=True,
			keep_trailing_newline=True,
			autoescape=False,
		)
	)


@cache
def environment() -> jinja2.Environment:
	"""The built-in templates' environment."""
	return _environment(str(data_path("templates")))


@cache
def profile_environment(directory: str) -> jinja2.Environment:
	"""An org profile's ``templates/``, rendered with the same configuration; a template reached
	through a symlink is refused."""
	return _environment(directory, links=False)


def _refused(what: str, e: SecurityError) -> ConfigError:
	return ConfigError(f"{what}: the template reaches outside its data, which the sandbox refuses: {e}")


def render_string(source: str, ctx: dict[str, Any]) -> str:
	"""A one-line template, such as an entry's ``path``."""
	try:
		return environment().from_string(source).render(**ctx)
	except SecurityError as e:
		raise _refused(repr(source), e) from e


def render(template: str, ctx: dict[str, Any], current: str | None, *, directory: Path | None = None) -> str:
	"""``template`` rendered for ``ctx``; ``current`` is the file on disk, which the floors read.

	``directory`` is an org profile's ``templates/`` to render it from instead of the built-in one.
	"""
	helpers = {
		"rev": lambda url, floor: floors.rev(current, url, floor),
		"pin": lambda action, sha, ver: floors.pin(current, action, sha, ver),
		"gen": configs.Gen(ctx),
	}
	env = profile_environment(str(directory)) if directory is not None else environment()
	try:
		return env.get_template(template).render(**ctx, **helpers)
	except SecurityError as e:
		raise _refused(f"templates/{template}", e) from e


# What a ``when`` may call, and how each operator of one compares.
_CALLS = {"len": len, "any": any, "all": all}
_COMPARE: dict[type[ast.cmpop], Callable[[Any, Any], Any]] = {
	ast.Eq: operator.eq,
	ast.NotEq: operator.ne,
	ast.Lt: operator.lt,
	ast.LtE: operator.le,
	ast.Gt: operator.gt,
	ast.GtE: operator.ge,
	ast.In: lambda a, b: a in b,
	ast.NotIn: lambda a, b: a not in b,
	ast.Is: operator.is_,
	ast.IsNot: operator.is_not,
}


def _evaluate(node: ast.expr, ctx: dict[str, Any], expr: str) -> Any:
	def ev(n: ast.expr) -> Any:
		return _evaluate(n, ctx, expr)

	def fail(why: str) -> ConfigError:
		return ConfigError(f"when {expr!r}: {why}")

	if isinstance(node, ast.Constant) and isinstance(node.value, str | int | float | bool | type(None)):
		return node.value
	if isinstance(node, ast.Name):
		if node.id.startswith("_") or node.id not in ctx:
			raise fail(f"{node.id!r} is not in the context")
		return ctx[node.id]
	if isinstance(node, ast.Attribute | ast.Subscript):
		base = ev(node.value)
		key = node.attr if isinstance(node, ast.Attribute) else ev(node.slice)
		if isinstance(key, str) and key.startswith("_"):
			raise fail(f"{key!r}: names starting with _ are not readable")
		if isinstance(node, ast.Attribute) and not isinstance(base, dict):
			raise fail(f".{key} of a value that is not a table")
		if not isinstance(base, dict | list | tuple | str) or isinstance(key, bool):
			raise fail(f"[{key!r}] of a value that has no items")
		try:
			return base[key]
		except (KeyError, IndexError, TypeError) as e:
			raise fail(f"no {key!r} there") from e
	if isinstance(node, ast.BoolOp):
		value: Any = None
		for operand in node.values:
			value = ev(operand)
			if isinstance(node.op, ast.And) and not value:
				return value
			if isinstance(node.op, ast.Or) and value:
				return value
		return value
	if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
		return not ev(node.operand)
	if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
		value = ev(node.operand)
		if isinstance(value, bool) or not isinstance(value, int | float):
			raise fail("unary minus needs a number")
		return -value
	if isinstance(node, ast.Compare):
		left = ev(node.left)
		for op, comparator in zip(node.ops, node.comparators, strict=True):
			right = ev(comparator)
			try:
				if not _COMPARE[type(op)](left, right):
					return False
			except TypeError as e:
				raise fail(str(e)) from e
			left = right
		return True
	if isinstance(node, ast.Call):
		if not isinstance(node.func, ast.Name) or node.func.id not in _CALLS or node.keywords:
			raise fail(f"only {', '.join(_CALLS)} may be called")
		if any(isinstance(a, ast.Starred) for a in node.args):
			raise fail("no * arguments")
		try:
			return _CALLS[node.func.id](*(ev(a) for a in node.args))
		except TypeError as e:
			raise fail(str(e)) from e
	if isinstance(node, ast.List | ast.Tuple):
		return [ev(e) for e in node.elts]
	raise fail(f"{type(node).__name__} is not allowed (see the spec's `when`)")


def evaluate(expr: str, ctx: dict[str, Any]) -> bool:
	"""A ``when`` (a manifest entry's, a retire rule's, an ``[[extra-files]]`` one): a Python
	expression over the context, read by a small evaluator rather than ``eval``.

	An org profile's ``when`` is data a pull request can change (an in-repo profile), and
	``--check`` evaluates it on untrusted PRs; restricting ``__builtins__`` is no sandbox. So
	only these are read: names of the context, ``.key`` and ``[key]`` on its values (never a
	name starting with ``_``), constants, lists and tuples, ``and``/``or``/``not``, unary
	minus, comparisons (``==``, ``!=``, ``<``, ``<=``, ``>``, ``>=``, ``in``, ``not in``,
	``is``, ``is not``) and calls of ``len``, ``any`` and ``all``. Anything else is exit 2."""
	try:
		tree = ast.parse(expr.strip(), mode="eval")
	except SyntaxError as e:
		raise ConfigError(f"when {expr!r} is not an expression: {e.msg}") from e
	return bool(_evaluate(tree.body, ctx, expr))
