"""Rendering: the one fixed Jinja configuration, the headers, and the template helpers.

The environment is fixed (spec §3.4): ``StrictUndefined``, ``trim_blocks``,
``lstrip_blocks`` and ``keep_trailing_newline``, templates read from
``frappe_nix_tools/data/templates`` through ``importlib.resources``, or from an org
profile's ``templates/`` for an override or an ``[[extra-files]]`` template (§8.1), with
the same configuration. Templates get:

- filters ``json`` / ``jsonc`` (oxfmt-formatted JSON), ``json_string`` (one quoted string),
  ``nix_string`` (a Nix string literal) and ``glob_to_regex`` (§2.14);
- functions ``rev(url, floor)`` and ``pin(action, sha, version)`` (floors, §3.2), bound to
  the file being rendered, and ``gen`` (``scaffold.configs.Gen``).
"""

import json
from functools import cache
from pathlib import Path
from typing import Any

import jinja2

from frappe_nix_tools.common import data_path
from frappe_nix_tools.scaffold import configs, floors, globs, jsonfmt

MARKER = "frappe-nix:managed"
BASE = f"{MARKER} — generated by frappe-nix (`frappe-init --sync`);"


def header(kind: str, local: bool, note: str = "") -> str:
	"""The managed header line for a ``kind`` of file (§3.6); empty for ``none``."""
	if kind == "none":
		return ""
	text = f"{BASE} {'edit only inside the frappe-nix:local region.' if local else 'do not edit.'}"
	if note:
		text += f" {note}"
	prefix = "//" if kind in ("jsonc", "ts") else "#"
	return f"{prefix} {text}\n"


def nix_string(value: str) -> str:
	escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${")
	return f'"{escaped}"'


def _configure(env: jinja2.Environment) -> jinja2.Environment:
	env.filters["json"] = lambda v: jsonfmt.dumps(v)
	env.filters["jsonc"] = lambda v: jsonfmt.dumps(v, jsonc=True)
	env.filters["json_string"] = lambda v: json.dumps(v, ensure_ascii=False)
	env.filters["nix_string"] = nix_string
	env.filters["glob_to_regex"] = globs.glob_to_regex
	return env


def _environment(directory: str) -> jinja2.Environment:
	return _configure(
		jinja2.Environment(
			loader=jinja2.FileSystemLoader(directory),
			undefined=jinja2.StrictUndefined,
			trim_blocks=True,
			lstrip_blocks=True,
			keep_trailing_newline=True,
			autoescape=False,
		)
	)


@cache
def environment() -> jinja2.Environment:
	"""The built-in templates' environment."""
	return _environment(str(data_path("templates")))


@cache
def profile_environment(directory: str) -> jinja2.Environment:
	"""An org profile's ``templates/``, rendered with the same configuration."""
	return _environment(directory)


def render_string(source: str, ctx: dict[str, Any]) -> str:
	"""A one-line template, such as an entry's ``path``."""
	return environment().from_string(source).render(**ctx)


def render(template: str, ctx: dict[str, Any], current: str | None, *, directory: Path | None = None) -> str:
	"""``template`` rendered for ``ctx``; ``current`` is the file on disk, which the floors read.

	``directory`` is an org profile's ``templates/`` to render it from instead of the built-in one.
	"""
	helpers = {
		"rev": lambda url, floor: floors.rev(current, url, floor),
		"pin": lambda action, sha, ver: floors.pin(current, action, sha, ver),
		"gen": configs.Gen(ctx),
	}
	env = profile_environment(str(directory)) if directory is not None else environment()
	return env.get_template(template).render(**ctx, **helpers)


def evaluate(expr: str, ctx: dict[str, Any]) -> bool:
	"""A manifest ``when``: a Python expression over the context, with no builtins but ``len``."""
	return bool(eval(expr, {"__builtins__": {"len": len, "any": any, "all": all, "True": True}}, dict(ctx)))
